// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: quote.proto

package quote_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuoteService_QuoteStreamResponse_ChangeType int32

const (
	QuoteService_QuoteStreamResponse_ADDED   QuoteService_QuoteStreamResponse_ChangeType = 0
	QuoteService_QuoteStreamResponse_UPDATED QuoteService_QuoteStreamResponse_ChangeType = 1
	QuoteService_QuoteStreamResponse_DELETED QuoteService_QuoteStreamResponse_ChangeType = 2
)

// Enum value maps for QuoteService_QuoteStreamResponse_ChangeType.
var (
	QuoteService_QuoteStreamResponse_ChangeType_name = map[int32]string{
		0: "ADDED",
		1: "UPDATED",
		2: "DELETED",
	}
	QuoteService_QuoteStreamResponse_ChangeType_value = map[string]int32{
		"ADDED":   0,
		"UPDATED": 1,
		"DELETED": 2,
	}
)

func (x QuoteService_QuoteStreamResponse_ChangeType) Enum() *QuoteService_QuoteStreamResponse_ChangeType {
	p := new(QuoteService_QuoteStreamResponse_ChangeType)
	*p = x
	return p
}

func (x QuoteService_QuoteStreamResponse_ChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuoteService_QuoteStreamResponse_ChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_quote_proto_enumTypes[0].Descriptor()
}

func (QuoteService_QuoteStreamResponse_ChangeType) Type() protoreflect.EnumType {
	return &file_quote_proto_enumTypes[0]
}

func (x QuoteService_QuoteStreamResponse_ChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuoteService_QuoteStreamResponse_ChangeType.Descriptor instead.
func (QuoteService_QuoteStreamResponse_ChangeType) EnumDescriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{0, 10, 0}
}

type QuoteService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QuoteService) Reset() {
	*x = QuoteService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quote_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuoteService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteService) ProtoMessage() {}

func (x *QuoteService) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteService.ProtoReflect.Descriptor instead.
func (*QuoteService) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{0}
}

type QuoteService_Quote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string                           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Carrier          string                           `protobuf:"bytes,2,opt,name=carrier,proto3" json:"carrier,omitempty"`
	Customer         *QuoteService_Customer           `protobuf:"bytes,3,opt,name=customer,proto3" json:"customer,omitempty"`
	CustomerRef      string                           `protobuf:"bytes,4,opt,name=customer_ref,json=customerRef,proto3" json:"customer_ref,omitempty"`
	CustomerContacts []*QuoteService_Customer_Contact `protobuf:"bytes,5,rep,name=customer_contacts,json=customerContacts,proto3" json:"customer_contacts,omitempty"`
	AvailableDate    string                           `protobuf:"bytes,6,opt,name=available_date,json=availableDate,proto3" json:"available_date,omitempty"`
	Product          string                           `protobuf:"bytes,7,opt,name=product,proto3" json:"product,omitempty"`
	CollectFrom      string                           `protobuf:"bytes,8,opt,name=collect_from,json=collectFrom,proto3" json:"collect_from,omitempty"`
	Origin           string                           `protobuf:"bytes,9,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination      string                           `protobuf:"bytes,10,opt,name=destination,proto3" json:"destination,omitempty"`
	CargoType        string                           `protobuf:"bytes,11,opt,name=cargo_type,json=cargoType,proto3" json:"cargo_type,omitempty"`
	IsDangerous      bool                             `protobuf:"varint,12,opt,name=is_dangerous,json=isDangerous,proto3" json:"is_dangerous,omitempty"`
	CanBeTurned      bool                             `protobuf:"varint,13,opt,name=can_be_turned,json=canBeTurned,proto3" json:"can_be_turned,omitempty"`
	IsKnown          bool                             `protobuf:"varint,14,opt,name=is_known,json=isKnown,proto3" json:"is_known,omitempty"`
	AircraftOnly     bool                             `protobuf:"varint,15,opt,name=aircraft_only,json=aircraftOnly,proto3" json:"aircraft_only,omitempty"`
	Description      string                           `protobuf:"bytes,16,opt,name=description,proto3" json:"description,omitempty"`
	SizeMetric       string                           `protobuf:"bytes,17,opt,name=size_metric,json=sizeMetric,proto3" json:"size_metric,omitempty"`
	WeightMetric     string                           `protobuf:"bytes,18,opt,name=weight_metric,json=weightMetric,proto3" json:"weight_metric,omitempty"`
	Cargo            []*QuoteService_Cargo            `protobuf:"bytes,19,rep,name=cargo,proto3" json:"cargo,omitempty"`
	Rate             *QuoteService_Rates_Rate         `protobuf:"bytes,20,opt,name=rate,proto3" json:"rate,omitempty"`
}

func (x *QuoteService_Quote) Reset() {
	*x = QuoteService_Quote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quote_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuoteService_Quote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteService_Quote) ProtoMessage() {}

func (x *QuoteService_Quote) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteService_Quote.ProtoReflect.Descriptor instead.
func (*QuoteService_Quote) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{0, 0}
}

func (x *QuoteService_Quote) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QuoteService_Quote) GetCarrier() string {
	if x != nil {
		return x.Carrier
	}
	return ""
}

func (x *QuoteService_Quote) GetCustomer() *QuoteService_Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *QuoteService_Quote) GetCustomerRef() string {
	if x != nil {
		return x.CustomerRef
	}
	return ""
}

func (x *QuoteService_Quote) GetCustomerContacts() []*QuoteService_Customer_Contact {
	if x != nil {
		return x.CustomerContacts
	}
	return nil
}

func (x *QuoteService_Quote) GetAvailableDate() string {
	if x != nil {
		return x.AvailableDate
	}
	return ""
}

func (x *QuoteService_Quote) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *QuoteService_Quote) GetCollectFrom() string {
	if x != nil {
		return x.CollectFrom
	}
	return ""
}

func (x *QuoteService_Quote) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *QuoteService_Quote) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *QuoteService_Quote) GetCargoType() string {
	if x != nil {
		return x.CargoType
	}
	return ""
}

func (x *QuoteService_Quote) GetIsDangerous() bool {
	if x != nil {
		return x.IsDangerous
	}
	return false
}

func (x *QuoteService_Quote) GetCanBeTurned() bool {
	if x != nil {
		return x.CanBeTurned
	}
	return false
}

func (x *QuoteService_Quote) GetIsKnown() bool {
	if x != nil {
		return x.IsKnown
	}
	return false
}

func (x *QuoteService_Quote) GetAircraftOnly() bool {
	if x != nil {
		return x.AircraftOnly
	}
	return false
}

func (x *QuoteService_Quote) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *QuoteService_Quote) GetSizeMetric() string {
	if x != nil {
		return x.SizeMetric
	}
	return ""
}

func (x *QuoteService_Quote) GetWeightMetric() string {
	if x != nil {
		return x.WeightMetric
	}
	return ""
}

func (x *QuoteService_Quote) GetCargo() []*QuoteService_Cargo {
	if x != nil {
		return x.Cargo
	}
	return nil
}

func (x *QuoteService_Quote) GetRate() *QuoteService_Rates_Rate {
	if x != nil {
		return x.Rate
	}
	return nil
}

type QuoteService_Customer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *QuoteService_Customer) Reset() {
	*x = QuoteService_Customer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quote_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuoteService_Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteService_Customer) ProtoMessage() {}

func (x *QuoteService_Customer) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteService_Customer.ProtoReflect.Descriptor instead.
func (*QuoteService_Customer) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{0, 1}
}

func (x *QuoteService_Customer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type QuoteService_Cargo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalPieces    int32                               `protobuf:"varint,1,opt,name=total_pieces,json=totalPieces,proto3" json:"total_pieces,omitempty"`
	TotalWeight    int32                               `protobuf:"varint,2,opt,name=total_weight,json=totalWeight,proto3" json:"total_weight,omitempty"`
	TotalVolume    int32                               `protobuf:"varint,3,opt,name=total_volume,json=totalVolume,proto3" json:"total_volume,omitempty"`
	Specifications []*QuoteService_Cargo_Specification `protobuf:"bytes,4,rep,name=specifications,proto3" json:"specifications,omitempty"`
}

func (x *QuoteService_Cargo) Reset() {
	*x = QuoteService_Cargo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quote_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuoteService_Cargo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteService_Cargo) ProtoMessage() {}

func (x *QuoteService_Cargo) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteService_Cargo.ProtoReflect.Descriptor instead.
func (*QuoteService_Cargo) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{0, 2}
}

func (x *QuoteService_Cargo) GetTotalPieces() int32 {
	if x != nil {
		return x.TotalPieces
	}
	return 0
}

func (x *QuoteService_Cargo) GetTotalWeight() int32 {
	if x != nil {
		return x.TotalWeight
	}
	return 0
}

func (x *QuoteService_Cargo) GetTotalVolume() int32 {
	if x != nil {
		return x.TotalVolume
	}
	return 0
}

func (x *QuoteService_Cargo) GetSpecifications() []*QuoteService_Cargo_Specification {
	if x != nil {
		return x.Specifications
	}
	return nil
}

type QuoteService_Rates struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QuoteService_Rates) Reset() {
	*x = QuoteService_Rates{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quote_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuoteService_Rates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteService_Rates) ProtoMessage() {}

func (x *QuoteService_Rates) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteService_Rates.ProtoReflect.Descriptor instead.
func (*QuoteService_Rates) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{0, 3}
}

type QuoteService_NoParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QuoteService_NoParams) Reset() {
	*x = QuoteService_NoParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quote_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuoteService_NoParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteService_NoParams) ProtoMessage() {}

func (x *QuoteService_NoParams) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteService_NoParams.ProtoReflect.Descriptor instead.
func (*QuoteService_NoParams) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{0, 4}
}

// v1
type QuoteService_QuoteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *QuoteService_QuoteRequest) Reset() {
	*x = QuoteService_QuoteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quote_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuoteService_QuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteService_QuoteRequest) ProtoMessage() {}

func (x *QuoteService_QuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteService_QuoteRequest.ProtoReflect.Descriptor instead.
func (*QuoteService_QuoteRequest) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{0, 5}
}

func (x *QuoteService_QuoteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type QuoteService_QuoteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Quote *QuoteService_Quote `protobuf:"bytes,1,opt,name=quote,proto3" json:"quote,omitempty"`
}

func (x *QuoteService_QuoteResponse) Reset() {
	*x = QuoteService_QuoteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quote_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuoteService_QuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteService_QuoteResponse) ProtoMessage() {}

func (x *QuoteService_QuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteService_QuoteResponse.ProtoReflect.Descriptor instead.
func (*QuoteService_QuoteResponse) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{0, 6}
}

func (x *QuoteService_QuoteResponse) GetQuote() *QuoteService_Quote {
	if x != nil {
		return x.Quote
	}
	return nil
}

type QuoteService_QuoteIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *QuoteService_QuoteIdResponse) Reset() {
	*x = QuoteService_QuoteIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quote_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuoteService_QuoteIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteService_QuoteIdResponse) ProtoMessage() {}

func (x *QuoteService_QuoteIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteService_QuoteIdResponse.ProtoReflect.Descriptor instead.
func (*QuoteService_QuoteIdResponse) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{0, 7}
}

func (x *QuoteService_QuoteIdResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type QuoteService_QuoteDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Respsone string `protobuf:"bytes,1,opt,name=respsone,proto3" json:"respsone,omitempty"`
}

func (x *QuoteService_QuoteDeleteResponse) Reset() {
	*x = QuoteService_QuoteDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quote_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuoteService_QuoteDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteService_QuoteDeleteResponse) ProtoMessage() {}

func (x *QuoteService_QuoteDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteService_QuoteDeleteResponse.ProtoReflect.Descriptor instead.
func (*QuoteService_QuoteDeleteResponse) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{0, 8}
}

func (x *QuoteService_QuoteDeleteResponse) GetRespsone() string {
	if x != nil {
		return x.Respsone
	}
	return ""
}

// v2
type QuoteService_QuotesListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Quotes []*QuoteService_Quote `protobuf:"bytes,1,rep,name=quotes,proto3" json:"quotes,omitempty"`
}

func (x *QuoteService_QuotesListResponse) Reset() {
	*x = QuoteService_QuotesListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quote_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuoteService_QuotesListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteService_QuotesListResponse) ProtoMessage() {}

func (x *QuoteService_QuotesListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteService_QuotesListResponse.ProtoReflect.Descriptor instead.
func (*QuoteService_QuotesListResponse) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{0, 9}
}

func (x *QuoteService_QuotesListResponse) GetQuotes() []*QuoteService_Quote {
	if x != nil {
		return x.Quotes
	}
	return nil
}

type QuoteService_QuoteStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Quote      *QuoteService_Quote                         `protobuf:"bytes,1,opt,name=quote,proto3" json:"quote,omitempty"`
	ChangeType QuoteService_QuoteStreamResponse_ChangeType `protobuf:"varint,2,opt,name=changeType,proto3,enum=quote.tool.QuoteService_QuoteStreamResponse_ChangeType" json:"changeType,omitempty"`
}

func (x *QuoteService_QuoteStreamResponse) Reset() {
	*x = QuoteService_QuoteStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quote_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuoteService_QuoteStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteService_QuoteStreamResponse) ProtoMessage() {}

func (x *QuoteService_QuoteStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteService_QuoteStreamResponse.ProtoReflect.Descriptor instead.
func (*QuoteService_QuoteStreamResponse) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{0, 10}
}

func (x *QuoteService_QuoteStreamResponse) GetQuote() *QuoteService_Quote {
	if x != nil {
		return x.Quote
	}
	return nil
}

func (x *QuoteService_QuoteStreamResponse) GetChangeType() QuoteService_QuoteStreamResponse_ChangeType {
	if x != nil {
		return x.ChangeType
	}
	return QuoteService_QuoteStreamResponse_ADDED
}

type QuoteService_Customer_Contact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *QuoteService_Customer_Contact) Reset() {
	*x = QuoteService_Customer_Contact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quote_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuoteService_Customer_Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteService_Customer_Contact) ProtoMessage() {}

func (x *QuoteService_Customer_Contact) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteService_Customer_Contact.ProtoReflect.Descriptor instead.
func (*QuoteService_Customer_Contact) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *QuoteService_Customer_Contact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QuoteService_Customer_Contact) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *QuoteService_Customer_Contact) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type QuoteService_Cargo_Specification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pieces      int32                          `protobuf:"varint,1,opt,name=pieces,proto3" json:"pieces,omitempty"`
	Dimensions  *QuoteService_Cargo_Dimensions `protobuf:"bytes,4,opt,name=Dimensions,proto3" json:"Dimensions,omitempty"`
	GrossWeight float32                        `protobuf:"fixed32,5,opt,name=gross_weight,json=grossWeight,proto3" json:"gross_weight,omitempty"`
}

func (x *QuoteService_Cargo_Specification) Reset() {
	*x = QuoteService_Cargo_Specification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quote_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuoteService_Cargo_Specification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteService_Cargo_Specification) ProtoMessage() {}

func (x *QuoteService_Cargo_Specification) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteService_Cargo_Specification.ProtoReflect.Descriptor instead.
func (*QuoteService_Cargo_Specification) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *QuoteService_Cargo_Specification) GetPieces() int32 {
	if x != nil {
		return x.Pieces
	}
	return 0
}

func (x *QuoteService_Cargo_Specification) GetDimensions() *QuoteService_Cargo_Dimensions {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *QuoteService_Cargo_Specification) GetGrossWeight() float32 {
	if x != nil {
		return x.GrossWeight
	}
	return 0
}

type QuoteService_Cargo_Dimensions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Length int32 `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	Width  int32 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height int32 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *QuoteService_Cargo_Dimensions) Reset() {
	*x = QuoteService_Cargo_Dimensions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quote_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuoteService_Cargo_Dimensions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteService_Cargo_Dimensions) ProtoMessage() {}

func (x *QuoteService_Cargo_Dimensions) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteService_Cargo_Dimensions.ProtoReflect.Descriptor instead.
func (*QuoteService_Cargo_Dimensions) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{0, 2, 1}
}

func (x *QuoteService_Cargo_Dimensions) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *QuoteService_Cargo_Dimensions) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *QuoteService_Cargo_Dimensions) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type QuoteService_Rates_Rate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	On        string  `protobuf:"bytes,1,opt,name=on,proto3" json:"on,omitempty"`
	CostMin   float32 `protobuf:"fixed32,2,opt,name=cost_min,json=costMin,proto3" json:"cost_min,omitempty"`
	CostRate  float32 `protobuf:"fixed32,3,opt,name=cost_rate,json=costRate,proto3" json:"cost_rate,omitempty"`
	SalesMin  float32 `protobuf:"fixed32,4,opt,name=sales_min,json=salesMin,proto3" json:"sales_min,omitempty"`
	SalesRate float32 `protobuf:"fixed32,5,opt,name=sales_rate,json=salesRate,proto3" json:"sales_rate,omitempty"`
	Currency  string  `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
}

func (x *QuoteService_Rates_Rate) Reset() {
	*x = QuoteService_Rates_Rate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quote_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuoteService_Rates_Rate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteService_Rates_Rate) ProtoMessage() {}

func (x *QuoteService_Rates_Rate) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteService_Rates_Rate.ProtoReflect.Descriptor instead.
func (*QuoteService_Rates_Rate) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{0, 3, 0}
}

func (x *QuoteService_Rates_Rate) GetOn() string {
	if x != nil {
		return x.On
	}
	return ""
}

func (x *QuoteService_Rates_Rate) GetCostMin() float32 {
	if x != nil {
		return x.CostMin
	}
	return 0
}

func (x *QuoteService_Rates_Rate) GetCostRate() float32 {
	if x != nil {
		return x.CostRate
	}
	return 0
}

func (x *QuoteService_Rates_Rate) GetSalesMin() float32 {
	if x != nil {
		return x.SalesMin
	}
	return 0
}

func (x *QuoteService_Rates_Rate) GetSalesRate() float32 {
	if x != nil {
		return x.SalesRate
	}
	return 0
}

func (x *QuoteService_Rates_Rate) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

var File_quote_proto protoreflect.FileDescriptor

var file_quote_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x71,
	0x75, 0x6f, 0x74, 0x65, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x22, 0xdb, 0x0f, 0x0a, 0x0c, 0x51, 0x75,
	0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x86, 0x06, 0x0a, 0x05, 0x51,
	0x75, 0x6f, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x12, 0x3d,
	0x0a, 0x08, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x21, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x2e, 0x51, 0x75,
	0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x52, 0x08, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12, 0x21, 0x0a,
	0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x66,
	0x12, 0x56, 0x0a, 0x11, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x63, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x71, 0x75,
	0x6f, 0x74, 0x65, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x2e, 0x43,
	0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x52, 0x10, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72,
	0x69, 0x67, 0x69, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x61, 0x72, 0x67,
	0x6f, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x64, 0x61, 0x6e, 0x67,
	0x65, 0x72, 0x6f, 0x75, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x44,
	0x61, 0x6e, 0x67, 0x65, 0x72, 0x6f, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x0d, 0x63, 0x61, 0x6e, 0x5f,
	0x62, 0x65, 0x5f, 0x74, 0x75, 0x72, 0x6e, 0x65, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0b, 0x63, 0x61, 0x6e, 0x42, 0x65, 0x54, 0x75, 0x72, 0x6e, 0x65, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x69, 0x73, 0x5f, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x69, 0x73, 0x4b, 0x6e, 0x6f, 0x77, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x69, 0x72, 0x63, 0x72,
	0x61, 0x66, 0x74, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c,
	0x61, 0x69, 0x72, 0x63, 0x72, 0x61, 0x66, 0x74, 0x4f, 0x6e, 0x6c, 0x79, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x10, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x18, 0x11, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x69, 0x7a, 0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12,
	0x23, 0x0a, 0x0d, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x18, 0x12, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x4d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x12, 0x34, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x18, 0x13, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x2e, 0x74, 0x6f, 0x6f, 0x6c,
	0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x61,
	0x72, 0x67, 0x6f, 0x52, 0x05, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x12, 0x37, 0x0a, 0x04, 0x72, 0x61,
	0x74, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x65,
	0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x52, 0x04, 0x72,
	0x61, 0x74, 0x65, 0x1a, 0x69, 0x0a, 0x08, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x1a, 0x49, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x1a, 0xb2,
	0x03, 0x0a, 0x05, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x5f, 0x70, 0x69, 0x65, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x69, 0x65, 0x63, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x21,
	0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x56, 0x6f, 0x6c, 0x75, 0x6d,
	0x65, 0x12, 0x54, 0x0a, 0x0e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x71, 0x75, 0x6f, 0x74,
	0x65, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x95, 0x01, 0x0a, 0x0d, 0x53, 0x70, 0x65, 0x63,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x69, 0x65,
	0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x69, 0x65, 0x63, 0x65,
	0x73, 0x12, 0x49, 0x0a, 0x0a, 0x44, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x2e, 0x74, 0x6f,
	0x6f, 0x6c, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x43, 0x61, 0x72, 0x67, 0x6f, 0x2e, 0x44, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x0a, 0x44, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x21, 0x0a, 0x0c,
	0x67, 0x72, 0x6f, 0x73, 0x73, 0x5f, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x0b, 0x67, 0x72, 0x6f, 0x73, 0x73, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x1a,
	0x52, 0x0a, 0x0a, 0x44, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c,
	0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x1a, 0xb0, 0x01, 0x0a, 0x05, 0x52, 0x61, 0x74, 0x65, 0x73, 0x1a, 0xa6, 0x01,
	0x0a, 0x04, 0x52, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x6f, 0x73, 0x74, 0x5f, 0x6d,
	0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x63, 0x6f, 0x73, 0x74, 0x4d, 0x69,
	0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x73, 0x74, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x63, 0x6f, 0x73, 0x74, 0x52, 0x61, 0x74, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x73, 0x61, 0x6c, 0x65, 0x73, 0x5f, 0x6d, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x08, 0x73, 0x61, 0x6c, 0x65, 0x73, 0x4d, 0x69, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x61, 0x6c, 0x65, 0x73, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x09, 0x73, 0x61, 0x6c, 0x65, 0x73, 0x52, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x1a, 0x0a, 0x0a, 0x08, 0x4e, 0x6f, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x1a, 0x1e, 0x0a, 0x0c, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x1a, 0x45, 0x0a, 0x0d, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x2e,
	0x51, 0x75, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x75, 0x6f,
	0x74, 0x65, 0x52, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x1a, 0x21, 0x0a, 0x0f, 0x51, 0x75, 0x6f,
	0x74, 0x65, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x1a, 0x31, 0x0a, 0x13,
	0x51, 0x75, 0x6f, 0x74, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x73, 0x6f, 0x6e, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x73, 0x6f, 0x6e, 0x65, 0x1a,
	0x4c, 0x0a, 0x12, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x06, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x2e, 0x74, 0x6f,
	0x6f, 0x6c, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x06, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x1a, 0xd7, 0x01,
	0x0a, 0x13, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x2e, 0x74, 0x6f, 0x6f,
	0x6c, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51,
	0x75, 0x6f, 0x74, 0x65, 0x52, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x12, 0x57, 0x0a, 0x0a, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x37, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x2e, 0x51, 0x75, 0x6f,
	0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x22, 0x31, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x44, 0x44, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45,
	0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x02, 0x32, 0xbf, 0x04, 0x0a, 0x09, 0x51, 0x75, 0x6f, 0x74,
	0x65, 0x54, 0x6f, 0x6f, 0x6c, 0x12, 0x59, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74,
	0x65, 0x12, 0x25, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x2e, 0x51,
	0x75, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x75, 0x6f, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x65,
	0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x57, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x12,
	0x1e, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x2e, 0x51, 0x75, 0x6f,
	0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x1a,
	0x28, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x2e, 0x51, 0x75, 0x6f,
	0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x49,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x0b, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x12, 0x1e, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x65,
	0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x1a, 0x28, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x65,
	0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x62, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x75, 0x6f, 0x74,
	0x65, 0x12, 0x25, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x2e, 0x51,
	0x75, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x75, 0x6f, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x65,
	0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5e, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x51, 0x75, 0x6f,
	0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x21, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x2e, 0x74,
	0x6f, 0x6f, 0x6c, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x4e, 0x6f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x2b, 0x2e, 0x71, 0x75, 0x6f, 0x74,
	0x65, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x61, 0x0a, 0x0c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x51, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x12, 0x21, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x2e, 0x74,
	0x6f, 0x6f, 0x6c, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x4e, 0x6f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x2c, 0x2e, 0x71, 0x75, 0x6f, 0x74,
	0x65, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x61, 0x71, 0x69, 0x77, 0x61, 0x71, 0x69,
	0x2f, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_quote_proto_rawDescOnce sync.Once
	file_quote_proto_rawDescData = file_quote_proto_rawDesc
)

func file_quote_proto_rawDescGZIP() []byte {
	file_quote_proto_rawDescOnce.Do(func() {
		file_quote_proto_rawDescData = protoimpl.X.CompressGZIP(file_quote_proto_rawDescData)
	})
	return file_quote_proto_rawDescData
}

var file_quote_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_quote_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_quote_proto_goTypes = []interface{}{
	(QuoteService_QuoteStreamResponse_ChangeType)(0), // 0: quote.tool.QuoteService.QuoteStreamResponse.ChangeType
	(*QuoteService)(nil),                             // 1: quote.tool.QuoteService
	(*QuoteService_Quote)(nil),                       // 2: quote.tool.QuoteService.Quote
	(*QuoteService_Customer)(nil),                    // 3: quote.tool.QuoteService.Customer
	(*QuoteService_Cargo)(nil),                       // 4: quote.tool.QuoteService.Cargo
	(*QuoteService_Rates)(nil),                       // 5: quote.tool.QuoteService.Rates
	(*QuoteService_NoParams)(nil),                    // 6: quote.tool.QuoteService.NoParams
	(*QuoteService_QuoteRequest)(nil),                // 7: quote.tool.QuoteService.QuoteRequest
	(*QuoteService_QuoteResponse)(nil),               // 8: quote.tool.QuoteService.QuoteResponse
	(*QuoteService_QuoteIdResponse)(nil),             // 9: quote.tool.QuoteService.QuoteIdResponse
	(*QuoteService_QuoteDeleteResponse)(nil),         // 10: quote.tool.QuoteService.QuoteDeleteResponse
	(*QuoteService_QuotesListResponse)(nil),          // 11: quote.tool.QuoteService.QuotesListResponse
	(*QuoteService_QuoteStreamResponse)(nil),         // 12: quote.tool.QuoteService.QuoteStreamResponse
	(*QuoteService_Customer_Contact)(nil),            // 13: quote.tool.QuoteService.Customer.Contact
	(*QuoteService_Cargo_Specification)(nil),         // 14: quote.tool.QuoteService.Cargo.Specification
	(*QuoteService_Cargo_Dimensions)(nil),            // 15: quote.tool.QuoteService.Cargo.Dimensions
	(*QuoteService_Rates_Rate)(nil),                  // 16: quote.tool.QuoteService.Rates.Rate
}
var file_quote_proto_depIdxs = []int32{
	3,  // 0: quote.tool.QuoteService.Quote.customer:type_name -> quote.tool.QuoteService.Customer
	13, // 1: quote.tool.QuoteService.Quote.customer_contacts:type_name -> quote.tool.QuoteService.Customer.Contact
	4,  // 2: quote.tool.QuoteService.Quote.cargo:type_name -> quote.tool.QuoteService.Cargo
	16, // 3: quote.tool.QuoteService.Quote.rate:type_name -> quote.tool.QuoteService.Rates.Rate
	14, // 4: quote.tool.QuoteService.Cargo.specifications:type_name -> quote.tool.QuoteService.Cargo.Specification
	2,  // 5: quote.tool.QuoteService.QuoteResponse.quote:type_name -> quote.tool.QuoteService.Quote
	2,  // 6: quote.tool.QuoteService.QuotesListResponse.quotes:type_name -> quote.tool.QuoteService.Quote
	2,  // 7: quote.tool.QuoteService.QuoteStreamResponse.quote:type_name -> quote.tool.QuoteService.Quote
	0,  // 8: quote.tool.QuoteService.QuoteStreamResponse.changeType:type_name -> quote.tool.QuoteService.QuoteStreamResponse.ChangeType
	15, // 9: quote.tool.QuoteService.Cargo.Specification.Dimensions:type_name -> quote.tool.QuoteService.Cargo.Dimensions
	7,  // 10: quote.tool.QuoteTool.GetQuote:input_type -> quote.tool.QuoteService.QuoteRequest
	2,  // 11: quote.tool.QuoteTool.CreateQuote:input_type -> quote.tool.QuoteService.Quote
	2,  // 12: quote.tool.QuoteTool.UpdateQuote:input_type -> quote.tool.QuoteService.Quote
	7,  // 13: quote.tool.QuoteTool.DeleteQuote:input_type -> quote.tool.QuoteService.QuoteRequest
	6,  // 14: quote.tool.QuoteTool.GetQuoteList:input_type -> quote.tool.QuoteService.NoParams
	6,  // 15: quote.tool.QuoteTool.StreamQuotes:input_type -> quote.tool.QuoteService.NoParams
	8,  // 16: quote.tool.QuoteTool.GetQuote:output_type -> quote.tool.QuoteService.QuoteResponse
	9,  // 17: quote.tool.QuoteTool.CreateQuote:output_type -> quote.tool.QuoteService.QuoteIdResponse
	9,  // 18: quote.tool.QuoteTool.UpdateQuote:output_type -> quote.tool.QuoteService.QuoteIdResponse
	10, // 19: quote.tool.QuoteTool.DeleteQuote:output_type -> quote.tool.QuoteService.QuoteDeleteResponse
	11, // 20: quote.tool.QuoteTool.GetQuoteList:output_type -> quote.tool.QuoteService.QuotesListResponse
	12, // 21: quote.tool.QuoteTool.StreamQuotes:output_type -> quote.tool.QuoteService.QuoteStreamResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_quote_proto_init() }
func file_quote_proto_init() {
	if File_quote_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_quote_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuoteService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quote_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuoteService_Quote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quote_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuoteService_Customer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quote_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuoteService_Cargo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quote_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuoteService_Rates); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quote_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuoteService_NoParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quote_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuoteService_QuoteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quote_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuoteService_QuoteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quote_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuoteService_QuoteIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quote_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuoteService_QuoteDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quote_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuoteService_QuotesListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quote_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuoteService_QuoteStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quote_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuoteService_Customer_Contact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quote_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuoteService_Cargo_Specification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quote_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuoteService_Cargo_Dimensions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quote_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuoteService_Rates_Rate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_quote_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_quote_proto_goTypes,
		DependencyIndexes: file_quote_proto_depIdxs,
		EnumInfos:         file_quote_proto_enumTypes,
		MessageInfos:      file_quote_proto_msgTypes,
	}.Build()
	File_quote_proto = out.File
	file_quote_proto_rawDesc = nil
	file_quote_proto_goTypes = nil
	file_quote_proto_depIdxs = nil
}
